git:
  submodules: false
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
#      env:
#        - COMPILER=g++-5
#      addons:
#        apt:
#          packages:
#            - g++-5
#            #- valgrind

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  - git submodule update --init --remote --recursive
  #  - sudo apt-get install -y libgtest-dev #valgrind

  # Update apt lists (in order to install boost 1.58+)
  - cat /etc/apt/sources.list
  - cp /etc/apt/sources.list /tmp/sources.list
  - echo 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - echo 'deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - sudo mv /tmp/sources.list /etc/apt/sources.list

  # Install boost 1.58+
  - sudo apt update
  - sudo apt install -y libboost-all-dev

install:
  - sudo apt install -y libboost-all-dev  #1.58
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script: "./scripts/build.sh"
#branches:
#  only:
#  - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T $TRAVIS_BUILD_DIR/build/homeworks_0.0."$TRAVIS_BUILD_NUMBER"_amd64.deb -ugvenewour:$BINTRAY_API_KEY "https://api.bintray.com/content/gvenewour/miscellaneous/homeworks/$TRAVIS_BUILD_NUMBER/homeworks_0.0."$TRAVIS_BUILD_NUMBER"_amd64.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"